# Role for Nginx reverse proxy
# This assumes Let's Encrypt certificates are present, see nginx.conf
---
- name: Stop nginx service
  systemd:
    name: nginx
    state: stopped
    enabled: no
  ignore_errors: yes

- name: Remove nginx package
  dnf:
    name: nginx
    state: absent

- name: Install dnf-utils
  dnf:
    name: dnf-utils
    state: present

- name: Install Nginx repo
  copy:
    src: nginx.repo
    dest: /etc/yum.repos.d/

- name: Install Nginx
  dnf:
    name: nginx-1.22.*
    state: present

# allow ports 80 and 443
- include_role:
    name: firewalld-allow-http-https

