---
- name: Unzip is installed.
  yum:
    name: unzip
    state: present

- name: Packer is downloaded and installed
  unarchive:
    src: https://releases.hashicorp.com/packer/1.3.2/packer_1.3.2_linux_amd64.zip
    dest: /usr/local/bin
    remote_src: yes
    creates: /usr/local/bin/packer