---
- include_role:
    name: firewalld-allow-http-https

# rootless podman cannot bind to privileged ports
- name: Allow binding privileged ports from 80 and up
  sysctl:
    name: net.ipv4.ip_unprivileged_port_start
    value: "80"
    sysctl_set: yes
    state: present
    reload: yes
