---
- name: map inventory IPs to .local hostnames
  lineinfile:
    dest: /etc/hosts
    regexp: ".*{{ item }}.local$"
    line: "{{ hostvars[item].ansible_host }} {{item}}.local"
    state: present
  when: hostvars[item].ansible_host is defined
  with_items: "{{ groups.all }}"