---
# Install nginx
- name: Stop nginx service
  systemd:
    name: nginx
    state: stopped
    enabled: no
  ignore_errors: yes

- name: Remove nginx package
  dnf:
    name: nginx
    state: absent

- name: Install dnf-utils
  dnf:
    name: dnf-utils
    state: present

- name: Install Nginx repo
  copy:
    src: nginx.repo
    dest: /etc/yum.repos.d/

- name: Install Nginx
  dnf:
    name: nginx-1.22.*
    state: present

# allow ports 80 and 443
- include_role:
    name: firewalld-allow-http-https

# Configure reverse proxy
- name: Copy Nginx reverse proxy config
  copy:
    src: nginx.conf
    dest: /etc/nginx/

- name: Enable and start Nginx service
  systemd:
    daemon_reload: yes
    name: nginx
    state: started
    enabled: yes

